export const component: string;
export const head: string;
export const logo: string;
export const title: string;
export const titleArrow: string;
export const sub: string;
export const active: string;
export const open: string;
export const hide: string;
